### ISSUE TITLE
Consider moving publications into a separate directory

### ISSUE THREAD

**Issue by u451f** [u451f/criticalinfrastructurelab#11]
How about we put all the CILs into a separate directory to separate the actual code from the output? Something like ./CIL/ so it's still easily accessible.

**Comment by maxigas** [comment]
Yes, it could be called "output" so that people who are not familiar with the cult could also recognise what purpose that directory serves. :)

**Comment by u451f** [comment]
Could you take care of that as you authored that bit and know it fairly well?

**Comment by maxigas** [comment]
Yes, i am doing it now.

**Comment by maxigas** [comment]
I am trying to push a commit but has to figure out how i can auth. with GitHub in this situation.

**Comment by maxigas** [comment]
Do we also need the print-automation.backup folder? I think i might have committed that by mistake at some point.

**Comment by u451f** [comment]
we don't :)

**Comment by maxigas** [comment]
OK i make another commit to delete that and a third one to correct a typo in the render.sh script.

**Comment by maxigas** [comment]
Done. Can this issue be closed now?

**Comment by maxigas** [comment]
Ah feel free to open if it is not working on your side!
