### ISSUE TITLE
Modernize CSS

### ISSUE THREAD

**Issue by u451f** [u451f/criticalinfrastructurelab#12]
currently we use "page-break-before" and consorts: https://developer.mozilla.org/en-US/docs/Web/CSS/break-before, and they've been renamed - but we need to check if the weasyprint engine accepts the new or the old name

**Comment by maxigas** [comment]
Please explain what are "consorts"!

The other issue is clear: "page-break-before" is depreciated now in favour of "break-before", and apparently they should both do the same thing. I can test if this works in the current setup under Debian `trixie` (testing).

The consort thing i need to be explained. :)

**Comment by maxigas** [comment]
For the record, I attach renders with both old and new names (they are byte-identical).
[CIL006_break-before.pdf](https://github.com/u451f/criticalinfrastructurelab/files/14304640/CIL006_break-before.pdf)
[CIL006_page-break-before.pdf](https://github.com/u451f/criticalinfrastructurelab/files/14304641/CIL006_page-break-before.pdf)

...which means the renaming works, so i pushed a commit with "break-before" in production.

Feel free to open this in case you can explain what are the "conforts"!

**Comment by u451f** [comment]
Thanks! nice!
