### ISSUE TITLE
Do some test prints and fix found issues

### ISSUE THREAD

**Issue by u451f** [u451f/criticalinfrastructurelab#7]
Check if the page bleed and margins in printed material are well respected.
The file size seems correct and includes the bleed, but does it also respect the margins?

**Comment by u451f** [comment]
Issues I discovered:

1- the cover seems to have a white hairline at the bottom. I'm unsure if that is related to our file size or if that's something related to the tools used in the pipeline, but it can easily be tested by changing our file:

![Bildschirmfoto vom 2023-12-05 19-16-56](https://github.com/u451f/criticalinfrastructurelab/assets/6314248/d821fc5b-0572-4435-9fc4-4458e5b8ae88)

**Comment by u451f** [comment]
Status: waiting for input from infralab

**Comment by maxigas** [comment]
Let me know when you are done with addressing the other pending issues and then I can initiative the test print run. :)

**Comment by u451f** [comment]
I looked into all of these and proposed fixes
