### ISSUE TITLE
pulled quotes after a paragraph with footnotes should be shifted to the top of the next page

### ISSUE THREAD

**Issue by u451f** [u451f/criticalinfrastructurelab#9]
The "Shifting terrain" report (https://zenodo.org/records/10229828) makes heavy use of pulled quotes and there seem to be some issues with that where the page breaks after the quote but that should never happen:

![Bildschirmfoto vom 2023-12-05 19-02-01](https://github.com/u451f/criticalinfrastructurelab/assets/6314248/f2ff03d1-0566-4c63-bfb2-107206db00cf)
![Bildschirmfoto vom 2023-12-05 19-02-09](https://github.com/u451f/criticalinfrastructurelab/assets/6314248/14465d80-935d-4630-a5e3-a0f2d0f0fa62)

**Comment by u451f** [comment]
- CIL005 page 18 pulled quotes lack a non indented 1st paragraph → that seems to be a general issue

**Comment by u451f** [comment]
> * CIL005 page 18 pulled quotes lack a non indented 1st paragraph → that seems to be a general issue

fixed this in 8379ecfe6dd9952104ae5477c2f9c3a067563fc9

**Comment by u451f** [comment]
We have in print.css fot .footnotes
    page-break-after: always;
but it seems to be ignored.

**Comment by u451f** [comment]
Let me reopen this: I implemented a really ugly workaround as nothing that works in a browser (using `clear, after: `etc.) seems to do. I basically force the paragraph after the pulled quote to have a negative margin and the pulled quote after the footnotes to not float. Can we try and see how this works out? I'm sure it will generate something a bit ugly when the pulled quote is less than 2 lines.

**Comment by maxigas** [comment]
OK i re-generate some of the reports on my side and report on CIL005 page 11 and 13 and see if there are other examples.

**Comment by maxigas** [comment]
Also this is gona be on Debian trixie (testing) rather than Debian stable (bookworm). :)

**Comment by maxigas** [comment]
![CIL005page13](https://github.com/u451f/criticalinfrastructurelab/assets/287700/7efc1d33-cc43-4029-83e5-b174d97e77a8)

**Comment by maxigas** [comment]
The old version is on the right side and the new version is on the left side.

**Comment by maxigas** [comment]
The line at the top of the pulled quote would be better if it aligned with the top of the main text i guess. But it is not falling below the main text any more, and also not on other pages. So the fix works.

**Comment by u451f** [comment]
003 has a pulled quote before a full page image

**Comment by u451f** [comment]
> 003 has a pulled quote before a full page image

hm, it looks like that is not true anymore
